<?php

require '/var/www/token.php';
define('X_API_KEY_TOKEN', ADVFRAMEWORK_TOKEN);
define('FACEBOOK_APP_TOKEN', ADVFRAMEWORK_FACEBOOK_TOKEN);
define('FACEBOOK_APP_TOKEN_DEV', ADVFRAMEWORK_FACEBOOK_TOKEN_DEV);
